### ISSUE TITLE
Rename "Crowdspot" section 'Denylist' and move within Community & Governance

### ISSUE THREAD

**Issue by vincenzospaghetti** [helium/docs#1057]
I want to add information about the Denylist as a page in this section...as well as add information about how to remove yourself from the denylist

> Removing yourself from the Denylist
> Download the Helium Wallet App and import your 12 words https://docs.helium.com/wallets/helium-wallet-app 
> Goto https://www.crowdspot.io/ and click login
> Scan the QR code using the phones Camera App to Login
> Click on Submit Denylist Request
> Select Removal
> Provide evidence and/or reasoning why you should not be on the DenyList
> Info on evidence https://docs.helium.com/mine-hnt/crowdspot/
> Click Create Submission

**Comment by samgutentag** [comment]
completed with pr #1059
