### ISSUE TITLE
Typo - Use the Helium Network

### ISSUE THREAD

**Issue by ekmurray** [helium/docs#118]
Should be "ready-to-use", not "read-to-use"

![image0](https://user-images.githubusercontent.com/37159463/106165755-45b19800-6140-11eb-8a0b-c8a6eb258b98.jpg)

**Comment by jthiller** [comment]
Looks like this has been fixed. Looking here: https://docs.helium.com

<img width="501" alt="image" src="https://user-images.githubusercontent.com/1965053/109205758-e5703f00-775b-11eb-9ade-4204ce694acb.png">
