### ISSUE TITLE
Landrush and Constant Stake

### ISSUE THREAD

**Issue by lthiery** [helium/docs#1228]
Currently, the Landrush explainer in the Realms section states:
```
For the first 10 days following the Solana migration, HNT holders are elegible to stake their HNT for a 'landrush' bonus of 3x the lock amount.

If a landrush stake is moved or split out of its original position after the first 10 days have lapsed, the landrush bonus is forfeited.
```

But how does this apply to a Constant stake? Do you maintain the landrush bonus forever?

**Comment by jthiller** [comment]
Does https://github.com/helium/docs/pull/1243 solve the issue for you?

**Comment by lthiery** [comment]
Yes, that clarifies. So all land rush bonus is done after 1 year?

**Comment by jthiller** [comment]
Only if you stake for 1 year. The maximum landrush bonus is 4 years. (with a 4 year lockup).

I'll take another look and see if this can be clarified.

-Joey Hiller

**Comment by lthiery** [comment]
Woops - I really just glanced at the new docs. User error
