### ISSUE TITLE
Console docs outline

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#13]
Overview

Devices
- Devices overview
- Adding new devices
    - Manually adding devices
    - Importing multiple devices
    - Importing devices from The Things Network
- Managing devices
    - Device Index overview
    - Adding and removing Labels
    - Searching for devices
    - Using the Quick Action menu
    - Pausing, Activating Devices
    - Editing display/view
    - Viewing live device data 
- Event logs and debugging
    - Managing event logs
        - Displaying
        - Exporting JSON files
    - Using Debug mode
        - Viewing
        - Exporting JSON files
        - Refreshing
        - Clearing

Labels
- Labels overview
- Adding and removing Labels
    - Devices
    - Integrations
    - Functions
- Managing Labels
    - Swapping Labels
    - Deleting Labels

Integrations
- Integrations overview
- Adding Integrations:
    - Prebuilt 
    - HTTP
    - MQTT 
    - AWS IoT
- Managing Downlinks
    - Downlink URLs, Keys
    - Manual Downlink
- Managing Integrations
- Adding and removing Labels

 Functions
- Functions overview
- Creating Decoder functions
    - Prebuilt
    - Custom
- Adding and removing Labels
- Managing Functions

Data Credits
- Data Credits overview
- Managing Data Credits
    - Acquiring with Credit Card
        - Setting up auto payment
        - Adding additional credit cards
    - Acquiring with $HNT
    - Transferring DC to Organizations

Organizations and Users
- Organization overview
- Managing Organizations
    - Adding 
    - Switching
    - Deleting
- Users overview
- Managing users
    - Inviting 
    - Changing permissions
    - Removing 

Settings
- Enabling 2FA 
- Generating API key

**Comment by PharkMillups** [comment]
Once we ship the latest, I'll go through this and create any new issues for specific works that still needs to be scheduled.

**Comment by PharkMillups** [comment]
Closing this. We've made a few new issues based on what's above.
