### ISSUE TITLE
Photo needs to be updated

### ISSUE THREAD

**Issue by Dumpling-girl** [helium/docs#1541]
https://docs.helium.com/use-the-network/devices/ready-to-use/dragino/rs485-bl/

Photo of the product, when you zoom in, is of the LSN50-V2.
I checked their website and dropbox, wrong picture in there too.

Maybe we can find another picture somewhere?

**Comment by jthiller** [comment]
It looks like this product is just an LSN50-V2 but configured to handle rs485. As-is, I don't think there is any change to make here for now.
