### ISSUE TITLE
Request Removal from Denylist

### ISSUE THREAD

**Issue by amirzda** [helium/docs#1627]
Please remove [Kind Crepe Cat] from Denylist

My Informations -----
My hotspot name is: Kind Crepe Cat
My hostspot b58 address is: 112M93PP6HUK7atXwBwaEBEBRvX3jwe5QY4bC6DZsK289D9uXrU1
My Discord handle is: amirzda#2660
My hotspot manufacturer is: Milesight-UG65

The removal reason: I have been using a helium miner for almost a year now, and all the information I have provided in the helium network has been honest and accurate. I have not made any mistakes or lied about anything, and I am sending you several photos as evidence for you to see and verify the authenticity of my claims. I still don't understand why I have been added to the denylist, and I haven't done anything specific that would warrant such action. I invested a significant amount of money to set up my miner, but unfortunately, I have never received that amount back from the miner. Now, seeing myself being added to the denylist in an illogical manner, I feel extremely frustrated. However, I hope this issue will be resolved as soon as possible.

![636deacb-3315-477e-ac2a-11fff4394a2d](https://github.com/helium/docs/assets/144738471/650503b9-3fb3-4ec3-b573-e59a11120428)
![b03de58e-dcca-4fea-8e71-96427ee1c90c](https://github.com/helium/docs/assets/144738471/8e607a71-093f-45f0-bc6f-9dbf5c3741f5)
![IMG_8009](https://github.com/helium/docs/assets/144738471/fd0b08fa-5249-43c1-8635-e46c1459fc9c)
![IMG_8010](https://github.com/helium/docs/assets/144738471/c871b510-0f71-47e7-8e46-2d1a6ffcd660)

[https://app.hotspotty.net/hotspots/112M93PP6HUK7atXwBwaEBEBRvX3jwe5QY4bC6DZsK289D9uXrU1/rewards](url)

My additional supporting info.

**Comment by jthiller** [comment]
This is not the right place for that request - please join the Helium Discord at https://discord.gg/helium and go to the #crowdspot-denylist channel there, and read the pinned messages.
