### ISSUE TITLE
Helium Ledger CLI

### ISSUE THREAD

**Issue by awesomepeopleeverywhere** [helium/docs#1685]
Hi, 

can anyone please help me with the issue of migrating HNT tokens which I have stored via "Helium Ledger CLI" (Using Nano Ledger S)? 

Because when I follow this post: https://docs.helium.com/solana/migration/wallet-user/
It asks you to use "Helium CLI Wallet [v1.7.11](https://github.com/helium/helium-wallet-rs/releases/tag/v1.7.11)" 

and there when you use the command "helium-wallet export --output qr" you are asked for a password. But I do not have a password because at the time of sending the HNT tokens to the wallet, I used nano Ledger s. And no password was required. 
![Uploading Password.jpg…]()

**Comment by abhay** [comment]
Have you had a look at this page yet? https://docs.helium.com/solana/migration/ledger

**Comment by awesomepeopleeverywhere** [comment]
Thank you that did the trick!
