### ISSUE TITLE
Create a policy to reject commits that have a hyperlink on the word "here"

### ISSUE THREAD

**Issue by DeflateAwning** [helium/docs#1690]
### Example 1

Bad practice: [Click here](https://google.com) to go to Google.

Way better: Visit [Google](https://google.com) to learn more.

### Example 2

Bad: Find the service on GitHub [here](https://github.com/disk91/helium-chirpstack-community)

Good: Find the [Disk91 Chipstack service on GitHub](https://github.com/disk91/helium-chirpstack-community)

### :(
I fixed up most instances of this a while ago, but someone keeps adding them (for an example, [click here](https://docs.helium.com/iot/run-an-lns/advanced-configuration)).

### Reasoning
This is an SEO advancement, as well as a speedreading thing. When you're looking for a link, it's way easier to find the link by reading the highlighted text. There's a miriad of other reasons to enforce this rule.

**Comment by jthiller** [comment]
I strongly agree. I think we could start to hammer out a 'docs style guide'

**Comment by jthiller** [comment]
Closing this issue to clean up the overall issues backlog, but continuing to track in #1740 as a priority.
