### ISSUE TITLE
In the top-left corner of the rendered docs (navbar), add "Docs" beside the logo

### ISSUE THREAD

**Issue by DeflateAwning** [helium/docs#1708]
On the Docs page, it's not totally clear that you're viewing the docs and not viewing the entire Helium website. This change of adding the word "Docs" or "Documentation" to the navbar would make that more clear!

**Comment by DeflateAwning** [comment]
Way better; I still feel like "Helium" should be in the navbar still though maybe? 

Might not be worth the effort to fix though.

**Comment by jthiller** [comment]
the [logo] [platform] pattern will show up in a couple other places, so this keeps things consistent.
<img width="352" alt="image" src="https://github.com/helium/docs/assets/1965053/fb68f840-53fc-4784-b184-3d571e52dcc7">
<img width="178" alt="image" src="https://github.com/helium/docs/assets/1965053/9c06a0da-ebf9-486a-88c9-0e3182479674">


I'd like to get some kind of link back to helium.com in there somewhere. It's helpful to tie marketing and docs pages together for new visitors.
