### ISSUE TITLE
Dead link to approved makers

### ISSUE THREAD

**Issue by cokes518** [helium/docs#176]
dead link: https://docs.helium.com/mine-hnt/approved-makers
came from here: https://docs.helium.com/mine-hnt/hotspot-makers/burn-hnt-to-maker-wallet/
<img width="696" alt="image" src="https://user-images.githubusercontent.com/19331274/108775799-76ee6f80-7516-11eb-8e7e-6b2d7ea1a0b3.png">

**Comment by lthiery** [comment]
Closed by #177
