### ISSUE TITLE
Document Datacake IoT platform integration

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#178]

**Comment by jdgemm** [comment]
@PharkMillups @illperipherals can we get some initial placeholder text for Datacake? Currently this link goes to dreaded 404 error on prod console: https://docs.helium.com/use-the-network/console/integrations/datacake

**Comment by davetapley** [comment]
I just set something up and it was as easy as [getting token like this](https://docs.datacake.de/api/generate-access-token) and putting in input on console integration page 🎉
