### ISSUE TITLE
Validator docker image instructions for mkdir needs fixing.

### ISSUE THREAD

**Issue by kellybyrd** [helium/docs#197]
https://docs.helium.com/mine-hnt/validators/validator-run/#docker-image has this:

> The validator directory should be created on a persistent ebs volume (if aws) or something similar that lives across server lifetimes.
`mkdir $HOME/validator_data; source=$HOME/validator_data`

I think the cmdline should be just
`mkdir $HOME/validator_data`

the `source` section isn't part of the cmdline it is used later in the docker cmdline.

**Comment by PharkMillups** [comment]
Fixed. Thanks!

**Comment by kellybyrd** [comment]
Just confirmed. Closing.
