### ISSUE TITLE
Potentially confusing step in testnet docs for noobs

### ISSUE THREAD

**Issue by kobiebotha** [helium/docs#199]
Meta: this issue is relatively miner and would only cause confusion for a first time user without prior experience. 

Details:
On [this](https://docs.helium.com/mine-hnt/validators/) page, the bullet list [referred to later as List A], at the bottom of the page seems to be written as steps to be followed top-down chronologically. However, on the first [step](https://docs.helium.com/mine-hnt/validators/validator-wallet/), under the "Stake Tokens" section,  there is a bullet item with instructions to "Obtain the validator node address:"

However as far as I can tell, this is actually a forward reference to the ["Run a Validator"](https://docs.helium.com/mine-hnt/validators/validator-run) section of List A. That is, someone following the steps in List A for the first time from top to bottom won't yet be able to run `miner peer addr`.

Maybe a simple forward reference would make this section of the docs more user friendly? I'm happy to submit a PR If this is an actual issue.

**Comment by PharkMillups** [comment]
Excellent feedback. One, single doc that covers the entire process end to end would be great. If you want to take a pass at it, please do. Otherwise I'll try to get to it later this week.

**Comment by PharkMillups** [comment]
I got antsy and am starting on this now. I'll send it your way for review when it needs some eyeball. :)

**Comment by PharkMillups** [comment]
WIP here if you want to take a look:

https://github.com/helium/docs/pull/203
