### ISSUE TITLE
BLE UUIDs are missing For Remove & Configured Services

### ISSUE THREAD

**Issue by ryanteck** [helium/docs#202]
The app has two new UUIDs which are not documented in the docs at https://docs.helium.com/mine-hnt/hotspot-makers/hotspot-ble-services/

These are ```8cc6e0b3-98c5-40cc-b1d8-692940e6994b``` and ```e125bda4-6fb8-11ea-bc55-0242ac130003```.

Ideally we need to know what the expected read and write responses are for these as a maker.

**Comment by kent-williams** [comment]
Hi @ryanteck,

We'll be sure to add that. If you are working on mimicking the BLE interface of the current hotspots I'd suggest using [gateway-config gatt characteristics](https://github.com/helium/gateway-config/tree/master/src) as your primary reference of the available services. Likewise I'd suggest using the [hotspot-app](https://github.com/helium/hotspot-app/blob/main/src/utils/bluetooth/bluetoothTypes.ts) as the primary interaction reference.

**Comment by ryanteck** [comment]
Yep we already have a mostly complete implementation of the interface with our own code. 

I did see both in the code and have started to implement them. However opened this issue as having a bit extra info on the expected info would be handy.

**Comment by kent-williams** [comment]
Great, thanks for opening!
