### ISSUE TITLE
Validator log dir has moved in latest build

### ISSUE THREAD

**Issue by rawrmaan** [helium/docs#207]
One can now do `tail -f ~/validator_data/log/console.log` instead of `docker exec validator tail -F /var/log/console.log`, as suggested in the validators troubleshooting page.

**Comment by jkowalcz** [comment]
So both of these would be correct.  The community seems to have moved to the former through out the Documentation. 

I believe this is explained well in "/mine-hnt/validators/troubleshooting" file.

If you agree you can close this issues out.

**Comment by samgutentag** [comment]
this was fixed, see https://docs.helium.com/mine-hnt/validators/troubleshooting/#view-logs for latest

thanks!
