### ISSUE TITLE
Validator docker latest build will constantly go outdated

### ISSUE THREAD

**Issue by rawrmaan** [helium/docs#208]
Currently the suggested docker run command is:

```
docker run -d \
--restart always \
--publish 2154:2154/tcp \
--name validator \
--mount type=bind,source=$HOME/validator_data,target=/var/data \
quay.io/team-helium/validator:miner-val-amd64_val0.1.7
```

It would probably be easier to point this to `latest-val-amd64` instead of `miner-val-amd64_val0.1.7` so it doesn't have to be constantly updated and folks don't land on old versions.

**Comment by jkowalcz** [comment]
@PharkMillups This has been updated in the docs to point to the proper tag now.

**Comment by PharkMillups** [comment]
Great. Closing.
