### ISSUE TITLE
make it clear validator stake transfers are only applicable to validators that have never staked

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#211]
Once a validator has unstaked it cannot be restaked, including transfers.

Validators can only have stake transferred to them if they haven't previously been staked.

If a validator has been staked, it's address is added to the blockchain and stake can't be transferred from another staked validator for security issues:

{
    "data": [
        {
            "created_at": "2021-03-04T04:16:21.858855Z",
            "failed_reason": "{invalid,already_exists}",
            "hash": "IL8VKwHgVqttlFnVINN3tXu-3n7oqiv6F7GkPaxZMxI",
            "status": "failed",
            "txn": {
                "amount": 0,
                "fee": 55000,
                "hash": "IL8VKwHgVqttlFnVINN3tXu-3n7oqiv6F7GkPaxZMxI",
                "new_address": "1YCLeGjXozePbcopBH4jbdxSDXTFhiqnZqosMU6hfDGDSK4CV2X",
                "new_owner": "1Wh4bh",
                "new_owner_signature": "",
                "old_address": "1Z9jpNw2rSQFfRz11VJEswBu1Hf1pmsjrbQE2uL54RMyTEuBPXh",
                "old_owner": "1bdQpyT4Qgxw5AZqixVw1eBgRSWTxkJRNc1GSaitCa4hU62Peij",
                "old_owner_signature": "O-AH10QCuYt-ZqpnZCnaLvG1-4_OdptvY6Yv6a2GG4NEEXUWlYSu7tAcbeIAakoFgI29NV4Q6YCAxhHYPQPFDw",
                "type": "transfer_validator_stake_v1"
            },
            "type": "transfer_validator_stake_v1",
            "updated_at": "2021-03-04T04:16:35.959607Z"

**Comment by jkowalcz** [comment]
@PharkMillups This note was added to docs/mine-hnt/validators/testnet/wallet.mdx

**Comment by PharkMillups** [comment]
Bang bang. Closing.
