### ISSUE TITLE
validator tutorial video 

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#220]
Provide a tutorial video to set up a validator node:

Include instructions for:

1. set up wallet
2. set up validator node
3. stake validator node
4. monitor and maintain validator node

**Comment by jthiller** [comment]
https://youtu.be/4szCWSDowro

**Comment by PharkMillups** [comment]
2nd one here. 

https://www.youtube.com/watch?v=S3eIIAPP9rk

Closing this for now. Adding both to docs. Thanks!
