### ISSUE TITLE
Update validator guide to have both amd64 + arm64 source build instructions

### ISSUE THREAD

**Issue by PharkMillups** [helium/docs#231]
Based on the suggestion from jackoat, let's make sure we have source build details for amd64 and arm64.

**Comment by jkowalcz** [comment]
@PharkMillups No ARM64 build instructions here : https://docs.helium.com/mine-hnt/validators/mainnet/deployment-guide/#deploy-miner-from-source

**Comment by PharkMillups** [comment]
I think we have this covered in docs. Closing for now.
