### ISSUE TITLE
docs still list previous docker version 

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#232]
believe the suggestion was to change to the latest or something similar...

docker run -d \
--restart always \
--publish 2154:2154/tcp \
--name validator \
--mount type=bind,source=$HOME/validator_data,target=/var/data \
quay.io/team-helium/validator:miner-val-**amd64_val0.1.15**

**Comment by jkowalcz** [comment]
@PharkMillups  This was added to the docker command. https://docs.helium.com/mine-hnt/validators/mainnet/deployment-guide/

**Comment by PharkMillups** [comment]
Love it. Closing.
