### ISSUE TITLE
Talk about Funding the Router in Run an OUI

### ISSUE THREAD

**Issue by lthiery** [helium/docs#244]

**Comment by mjohngreene** [comment]
Hey, @lthiery.  Curious if this relates to content at https://docs.helium.com/use-the-network/run-console and, if so, if the content on that link is the "latest."  

Also, I am trying to better understand the OUI functionality.  Which Discord channel might be best to ask related questions?

**Comment by lthiery** [comment]
Hi @mjohngreene 
#console is probably best on Discord - feel free to tag me (L0u15#0260)  as I don't often check-in otherwise.

Yes, that section is most relevant, in particular: https://docs.helium.com/use-the-network/run-console/#create-data-credits

I'm actually going to call this issue closed as community members have done a good job beefing up that section IMO
