### ISSUE TITLE
[META] Validator Docs Reorg Structure

### ISSUE THREAD

**Issue by PharkMillups** [helium/docs#248]
Moving discussion here from discord. Current proposed structure is this, in this order.

(I'll create new issues once we have things nailed.)

```
- Validator Overview / Intro 
- Technical Requirements
- Validator Deployment Guide 
- Monitoring
-- Basic Monitoring 
-- Troubleshooting 
- CLI and API 
-- API (Links to the API Docs)
-- Wallet CLI Docs
-- Miner CLI Docs
- FAQ and Resources 
-- FAQs
-- Videos
-- Blogs
```

I'm in favor of writing CLI docs that just demonstrate validator and miner usage but can be argued off this. Updating them in more than one place is not ideal so we could just link to the github repos as needed.

**Comment by jkowalcz** [comment]
@PharkMillups This is mainly done, need CLI documentation

**Comment by PharkMillups** [comment]
Ok. Closing. We'll spin a new issue for CLI docs as needed.
