### ISSUE TITLE
validators: clarity around consequences of unstaking

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#251]
Once a user unstakes a validator node, they must wait approx. 5 months before their stake is returned.

During that time they cannot restake a node or transfer it to another node. In addition, no rewards. 

To ensure clarity provide a warning and confirmation with unstaked content.

Warning! Once a validator has unstaked it enters an unbonding state. During this approximately 5 month (250,000 blocks) unbonding state, the staked amount cannot be transferred or withdrawn and validator nodes do NOT earn rewards. After the unbonding state has passed the original validator stake is returned to the owner’s wallet.

**Comment by jkowalcz** [comment]
@PharkMillups This is very well documented, but we will never get it obvious enough for everyone...

**Comment by PharkMillups** [comment]
Band-aids don't fix bullet holes
You say sorry just for show.
You live like that, you live with ghosts.

Closing.
