### ISSUE TITLE
"Use THe Network Devices" docs could use some update tweaks, eg: reference console decoder

### ISSUE THREAD

**Issue by leroyle** [helium/docs#281]
There are some minor updates that can be made to the devices docs, 
- one such is "something" that speaks to a console decoder script file for the documented device samples. Either a pointer to the decoder repo or probably better add a sample decoder along side the example source code.
- Heltec ESP32 doc needs words about adding a channelsMask define to the main sketch
- We should address commenting out device side ADR code for Heltec Cube cell now that ADR is supported.

- Cubecell -  existing how-to/code should explicitly state those samples are not usable for the mapper effort. Apparently there has been some newbie confusion.  Perhaps we should drop the mapper code into the repos?

- I will ask the dev community for more suggestions
- You can assign this issue to me for working, leroyle

**Comment by llang629** [comment]
The decoder code example for the LGT92 [show here](https://docs.helium.com/use-the-network/coverage-mapping/mappers-quickstart/) yields incorrect latitude and longitude values, at least for devices with firmware version 1.6.5.

Also, the mapper API does not expect values for roll, pitch, battery voltage, or alarm.

This decoder code seems to work properly:

```
function Decoder(bytes, port) {
   // Decode an uplink message from a buffer
   // (array) of bytes to an object of fields.
   var latitude  = (bytes[0] << 24 | bytes[1] << 16 | bytes[2] << 8 | bytes[3]) / 1000000;
   var longitude = (bytes[4] << 24 | bytes[5] << 16 | bytes[6] << 8 | bytes[7]) / 1000000;
   return {
     accuracy: 3,
     altitude: 0,
     latitude: latitude,
     longitude: longitude
   };
 }
```

**Comment by samgutentag** [comment]
thanks for this! We’ll be making a broader update to the device doc pages and will capture this input there. Closing this issue, and appreciate you taking the time.
