### ISSUE TITLE
CLI Wallet Docs: Describe the process for decoding the seed words from a basic wallet

### ISSUE THREAD

**Issue by mpkogli** [helium/docs#285]
In my case, I've created a wallet using the CLI: `./helium-wallet create basic` and a passphrase.

I'd like to access this wallet via the Helium App which requires my seed words. After reading the available documentation and searching/consulting on Discord, I'm at a loss about how to do this. Additional documentation would be helpful.

Thank you!

**Comment by abhay** [comment]
Unfortunately a CLI created key is not compatible with the app today. The app uses a 12 BIP32 word based seed.
