### ISSUE TITLE
HNT Token Economic Concepts Callout Date for blocks/1

### ISSUE THREAD

**Issue by sustakat** [helium/docs#290]
This link has a callout.
https://docs.helium.com/blockchain/helium-token/#hnt-token-economic-concepts

_**In the below issuance schedule, year 1 starts on August 1, 2020. Therefore the first halving will happen on day one of year three, which is August 1, 2021.**_

https://explorer.helium.com/blocks/1
= 29 JUL 2019, 5:44PM

... seems this is off by 1 year + according to the schedule for halving ... unless there was some other intent / year zero.

**Comment by PharkMillups** [comment]
Thanks. We'll get this fixed.

**Comment by jkowalcz** [comment]
@PharkMillups  this is moot at this time as it happened on Aug 1 2021
