### ISSUE TITLE
No HNT was produced in the genesis block

### ISSUE THREAD

**Issue by allenan** [helium/docs#291]
> The Helium Token is the native cryptocurrency and protocol token of the Helium blockchain. Its symbol is HNT. The first HNT was produced on July 29th, 2019 at 09:43PM UTC as part of the genesis block that was mined with the Helium Network launch. Prior to this date, there was no premine of HNT.

https://docs.helium.com/blockchain/helium-token/

The way this is stated is incorrect. The first 0.35 HNT were mined in [block 93](https://explorer.helium.com/txns/sEP-cbb2tvSrfbBleT21yGDNM8FIjNr3UT3k3BeZELw). Creating tokens in a genesis block would be considered a premine. Every token in existence today was mined.

**Comment by PharkMillups** [comment]
Excellent catch, Blockchain Bones. Fixed in that PR above.
