### ISSUE TITLE
Borken links to insiders

### ISSUE THREAD

**Issue by snip** [helium/docs#298]
On following pages, there is a link to https://www.helium.com/insider (which doesn't exist):
https://docs.helium.com/
https://docs.helium.com/community-governance

It was introduced in the documentation in Feb by: https://github.com/helium/docs/commit/9b703e44c5ecdd12bfd86bea4d3f450842e6bd8b

It was existing in the past (as an example: https://webcache.googleusercontent.com/search?q=cache:4gEJbFk7fnkJ:https://www.helium.com/insider+&cd=1&hl=en&ct=clnk&gl=fr)

I haven't found if it is still relevant to keep "insiders".

**Comment by said026** [comment]
I totally agree with your remark, I think it's better to comment the "Insiders" part of the documentation (if there's a plan to resume the program), as it introduces confusion for newcomers :)

**Comment by rsisto** [comment]
Just checked and the insiders link is not working.

**Comment by samgutentag** [comment]
insiders documentation was removed #725, closing issue
