### ISSUE TITLE
[question] AMI and storage recommendations

### ISSUE THREAD

**Issue by rootulp** [helium/docs#300]
Hi Helium! I have a few questions about the docs that came up when I set up a testnet validator:

> Depending on how you installed Docker in your system, it'll start on boot. In the AWS AMI above, we use systemd (systemctl status docker to check).

An AWS AMI is not mentioned above in the documentation. Is there an AMI that is recommended? I used **Amazon Linux 2 AMI**.

> Storage: 256 GB or more for mainnet. 64GB is sufficient for testnet.

Do you have guidance on how this storage is provisioned? I used an 8GB root volume and an additional 64GB EBS volume mounted at `/home/ec2-user/validator_data`. Does that look alright?

Keep up the great work team! I'm happy to submit a PR to clarify the docs based on the discussion in this issue.

**Comment by jkowalcz** [comment]
@PharkMillups This was covered in the testnet and main net deployment guides in a general fashion as AMI's are outdated the instant you put them in a document, just about.

**Comment by PharkMillups** [comment]
Roger. Closing.
