### ISSUE TITLE
Need to clarify/update CG election rules

### ISSUE THREAD

**Issue by cuteogre** [helium/docs#323]
CG election rules in the docs imply that a hotspot cannot be in a CG for more than 4 epochs as seen/implied in these paragraphs:

- Once elected, a Hotspot can typically be part of up to **four** consecutive Consensus Groups.
- Poorly performing CG members are likely to be deselected before their **four epoch limit** is reached.- 
- Once a Hotspot is deselected from a Consensus Group, it's not eligible to be elected to another group until the other 15 members that were in its group are completely cycled out. This would be **four elections** into the future.

From discussions on discord about some hotspots being on the CG for hours and even one up to 28 hours, it looks like this isn't the case and one admin mentioned that there is actually no limit.

Would be good to update this to what the rules actually are (even though validators are coming soon) because this is causing confusion for those people that notice this. :)

**Comment by cuteogre** [comment]
Just wanted to add that it looks like the rejoining rule ("not eligible ... until other members that were in its group are completely cycled out") isn't implemented either? i.e. You can be re-elected to the CG right after you were removed if you are lucky enough.

I got this from a user on helium discord so I'm not sure if that is true or not, but if it isn't, that rule should be updated too

**Comment by wolfenhawke** [comment]
Clarity leads to transparency. This is good. If it points to a development need, then that is good too.

**Comment by samgutentag** [comment]
thank you for filing this issue, some time has passed and with Validators being online, much has changed!  We will be taking this feedback into account with further documentation. thank you!
