### ISSUE TITLE
Console docs hold_time

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#327]
We will be adding a new field `hold_time` to the data sent to integrations. 

`hold_time` represents the time that a Hotspot was holding on to a packet (in milliseconds). The holding time can be due to multiple reasons such as: time between offer and acceptance of packet or if communication between Console/Router and Hotspots is slow then Hotspots would hold on to packets until communication is restored.

Why didn't we just subtract hold_time from reported_at?

Simply because a miner can never really be fully trusted in a decentralized network.

It is up to the user to decide a threshold at which hold_time should be included in time calculation or not.

hold_time will be included in each hotspot object:

"hotspots": [
        {
            "channel": 11,
            "frequency": 904.5,
            "id": "XXXXX",
            "lat": 0,
            "long": 0,
            "name": "late-red-ant",
            "reported_at": 1619562788361,
            "hold_time": 250,
            "rssi": -61,
            "snr": 9.199999809265137,
            "spreading": "SF7BW125",
            "status": "success"
        }
    ],

Router’s readme for full example of payload: https://github.com/helium/router#integrations-data

**Comment by samgutentag** [comment]
Closing with the author in preparation for console sunsetting.
