### ISSUE TITLE
Mismatch between lorawan-on-helium/frequency-plans/frequency-plans and countries_reg_domains

### ISSUE THREAD

**Issue by BenoitDuffez** [helium/docs#332]
The table here: https://github.com/helium/docs/blob/master/docs/lorawan-on-helium/frequency-plans/frequency-plans.mdx

doesn't match what the miner will use: https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv

e.g. Colombia is listed as US915 (902-928) on the docs but AU915 (915-928) in the CSV file.

**Comment by BenoitDuffez** [comment]
Colombia fixed with https://github.com/helium/docs/pull/342 but there are others pending (Bolivia, Costa Rica, Ecuador for example)

**Comment by shawaj** [comment]
@BenoitDuffez i updated the miner CSV in https://github.com/helium/miner/pull/772 to match the latest LoRa Spec RP002-1.0.3

But I think the table for "Frequency Plans by Country" and the listing about "Frequency Plans" in general needs updating here as you say... https://github.com/helium/docs/blob/master/docs/lorawan-on-helium/frequency-plans/frequency-plans.mdx

Will give it a first go this evening and submit for yours (and others) review

**Comment by shawaj** [comment]
Created #345 which brings it in to line with CSV updated in https://github.com/helium/miner/pull/772

**Comment by caleiton** [comment]
Currently there are no hotspots deployed in Costa Rica, but I know people whom already purchased the US915 model and they are waiting shipping. There is a difference between RP002-1.0.3 document, which says Costa Rica is AS-923-1. However in other documents we see Costa Rica as US902-928 which in theory is compatible with US915. https://docs.helium.com/lorawan-on-helium/frequency-plans/
Will the US915 will work on CR?

**Comment by shawaj** [comment]
@caleiton the LoRa doc is correct

**Comment by caleiton** [comment]
So people installing US915 devices here as they were following the existing document,  those hotspots won't be accepted by the Helium network?

**Comment by shawaj** [comment]
It would need to be as923-1 yes

**Comment by samgutentag** [comment]
closing resolved issue
