### ISSUE TITLE
Suggest adding documentation for uplink response messages

### ISSUE THREAD

**Issue by mpkogli** [helium/docs#339]
In https://github.com/helium/docs/blob/master/docs/use-the-network/console/debug.mdx, suggest additional documentation regarding category and subcategory status codes in the uplink response message from Console. In my ineptitude, I found it difficult to interpret `uplink_dropped/uplink_dropped_device_inactive` as the fact the device needed to be turned 'on' in Console and was unable to find any documentation. Thanks @jas for the assist.

**Comment by MedadRufus** [comment]
Just ran into the same problem. Solution was to "turn on" the device, with the slider on the interface:
![image](https://user-images.githubusercontent.com/26815217/143655786-37badbe1-721f-4da5-af60-e67b7f5339a0.png)

**Comment by samgutentag** [comment]
closing this issue, feedback will be included in future updates 👍
