### ISSUE TITLE
How to docker run create the extra mount point for the config? what's the target path of config？

### ISSUE THREAD

**Issue by Heltec-Aaron-Lee** [helium/docs#367]
In this page https://docs.helium.com/mine-hnt/hotspot-makers/docker-integration/.

Enable ECC608 and D-Bus

You will also want to add a few arguments to your Docker run command which create the extra mount point for the config, connect the i2c-device to the Docker container, and connect D-bus to the Docker container: 
How to docker run create the extra mount point for the config? what's the target path of config？
 --device /dev/i2c-1
 --net host
 --privileged
 -v /var/run/dbus:/var/run/dbus
 --mount type=bind,source=/home/ubuntu/miner_data,target=/var/data \

**Comment by samgutentag** [comment]
closing stale issue.

see latest docs for updated information https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/docker-integration/#enable-ecc608-and-d-bus
