### ISSUE TITLE
Validator: content to add to Wallet section

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#370]
Content to include in Validator Wallet section:

You can use existing Mainnet CLI wallets to stake validator nodes. If you want to create a new wallet, simply download and follow set up instructions in docs. 

If you want to continue to use the Testnet wallet you'll need to first delete or move the Testnet key (wallet.key) before creating a new Mainnet key (wallet create).

**Comment by samgutentag** [comment]
Closing with the author in preparation for validator sunsetting.
