### ISSUE TITLE
Add Microshare IoT platform integration

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#390]
Add new Microshare IoT platform pre-built integration to Console Integration section: https://docs.helium.com/use-the-network/console/integrations/

**Comment by illperipherals** [comment]
https://github.com/helium/docs/commit/cb90acbf501fa0192376158285f1e65141b76c6b
https://github.com/helium/docs/commit/c197ac78bd3cad96108ad4e02391d024b259fdf9
