### ISSUE TITLE
Add OSS validator tooling to validator docs

### ISSUE THREAD

**Issue by PharkMillups** [helium/docs#398]
e.g. 

https://github.com/tedder/miner_exporter/blob/main/miner_validator_stats_howto.md

**Comment by PharkMillups** [comment]
Another one. 

https://github.com/Factoshi/helium-exporter

**Comment by samgutentag** [comment]
with the migration to Solana and the pending dissolution of Validators, this documentation is no longer needed.

(Phark!)
