### ISSUE TITLE
Document Discord Roles

### ISSUE THREAD

**Issue by PharkMillups** [helium/docs#451]
Probably put it here

https://docs.helium.com/community-governance#discord

**Comment by rdmcolorz** [comment]
Hi I'm a fellow miner and software developer, I'd like to get started to contribute to the open-source project so I'd like to work on this :)

Questions:
1. Should this be a list of roles (Admin, moderators, etc) and what they represent?
From my personal deductions:
- Admin: Helium team members
- Moderators: Helium elected moderators
- Community developer: Open source contributors and Community App developers
- Patrons: Anyone who has deployed 15 or more Hotspots
- Hotspot owner: Anyone who has deployed one or more Hotspots
- Insiders: Insiders are the network's local connection to growing communities that aim to expand wireless coverage in their towns and cities

**Comment by jthiller** [comment]
@rdmcolorz 
Here are all of the roles currently used on the Helium Discord:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/1965053/125674191-18710769-585b-4004-b92e-ef2662302555.png">
<img width="297" alt="image" src="https://user-images.githubusercontent.com/1965053/125674241-a63920a5-e1f1-4527-ad90-01c22e20915e.png">
Many of them are just operational – roles for internal teams or bots.

**Comment by rdmcolorz** [comment]
thanks! I've posted a PR for this update

**Comment by DanielChrobak** [comment]
I'd just like to ask what Zapier is

**Comment by UrsaarDev** [comment]
> Probably put it here
> 
> https://docs.helium.com/community-governance#discord

👋🏻 Good day, mates.
I make the following utilities based on Solidity & Rust with powerful frontend demonstration.
💻Dapps(Swap, Staking, Referral, Farm, Pool, Presale, Reflection, DAO ...)
💻NFT marketplaces (Opensea, Rarible, Metaplex)
💻Backend software
Leave msgs if you are in the demand of me.

**Comment by samgutentag** [comment]
Closing stale issue
