### ISSUE TITLE
Dead Link in Helium App section of the Wallets page

### ISSUE THREAD

**Issue by mikedsp** [helium/docs#474]
![20210701_WalletdeadlinkScreenshot](https://user-images.githubusercontent.com/47757569/124094130-7adf5080-da26-11eb-9eb3-8f2c6761064c.jpg)
Steps to Reproduce
1. Go to https://docs.helium.com/wallets/#helium-app
2. Select the link 'our help website here' in the Helium App section of the page

Expected Result: Land on a page with more information about the Helium Wallet app
Actual Result: Land on a page with the URL below that says 'That page isn't here any more'
                             https://intercom.help/heliumnetwork/en/articles/3287804-app-overview

**Comment by PharkMillups** [comment]
Thanks for finding. If you have a minute to submit a pull request, that would be great. Just remove the entire line (as we just migrated over to these docs). If you don't have time, someone will pick it up soon.

**Comment by Patil2099** [comment]
I would love to work on this

**Comment by samgutentag** [comment]
link no longer included on this page, closing
