### ISSUE TITLE
Dead links to Light Hotspot installation instructions

### ISSUE THREAD

**Issue by tonycsa** [helium/docs#481]
links to installation instructions for Kerlink and Dragino are Dead
[https://docs.helium.com/use-the-network/light-hotspots/](url)

[https://docs.helium.com/mine-hnt/light-hotspots/guides/dragino/](url)

[https://docs.helium.com/mine-hnt/light-hotspots/guides/kerlink/](url)

**Comment by shawaj** [comment]
These are all working now it seems https://docs.helium.com/mine-hnt/data-only-hotspots/

**Comment by samgutentag** [comment]
links all good, closing this issue. thank you for your contribution!
