### ISSUE TITLE
Clarify port forwarding section

### ISSUE THREAD

**Issue by sullyjman** [helium/docs#519]
https://docs.helium.com/troubleshooting/network-troubleshooting/

Lots of people are reading the above and not understanding there is a difference between inbound/outbound.  I would recommend putting in a a note to state all home routers allow 22, 443 and 44158 outbound by default and in a majority of cases they only need to port forward 44158.

This is a huge risk as people are exposing their miners to the internet/botnets that are gonna try to brute force their way in.

Maybe have an advance section that states if you have a firewall that supports egress firewall rules to make sure 22/443 is open

**Comment by samgutentag** [comment]
Closing Issue, Port Forwarding is no longer necessary.
