### ISSUE TITLE
Validator icon missing (404): https://docs.helium.com/mine-hnt

### ISSUE THREAD

**Issue by ke6jjj** [helium/docs#620]
The `/mine-hnt` references a `https://docs.helium.com/img/validators/runvalidator.png`, which currently returns 404.

**Comment by kent-williams** [comment]
Hi @ke6jjj, can you point out which exact line number in which doc is referencing the incorrect img link please.

https://docs.helium.com/img/validators/runvalidator.png works

**Comment by samgutentag** [comment]
image links all resolve, closing this issue
