### ISSUE TITLE
deadlink to API for list of OUIs

### ISSUE THREAD

**Issue by mjohngreene** [helium/docs#653]
Last link at https://docs.helium.com/use-the-network/buy-an-oui/ returns "{"error":"Bad Request"}"

**Comment by PharkMillups** [comment]
Thanks, John. Both those links in the last sentence can be consolidated to just point here:

https://api.helium.io/v1/ouis

E.g. 

`When it is complete, you should also see your OUI as the most recently purchased and [on this list here](https://api.helium.io/v1/ouis)`.

Got a few minutes to put together a PR?

**Comment by mjohngreene** [comment]
👌 I'll do the PR this PM (presuming I can figure out how!)

Thanks for the speedy reply.

**Comment by samgutentag** [comment]
resolved in PR #654
closing
