### ISSUE TITLE
Add info about what happens when you reach the end of cursors

### ISSUE THREAD

**Issue by HeliumMonitor** [helium/docs#680]
On the [Blockchain API introduction page](https://docs.helium.com/api/blockchain/introduction) where it talks about cursors, it should mention what happens when you reach the last page. Does the GET request stop returning a cursor value, does it return a null cursor value, or something else?

**Comment by samgutentag** [comment]
Thank you for this contribution, additional information has been added. #910

**Comment by HeliumMonitor** [comment]
This is helpful, but I think it would be better to specify explicitly either:
1. The value of the `cursor` key is `null` in the associative array.
2. ... at which point no cursor is returned (i.e., there is no cursor key in the return associative array).
