### ISSUE TITLE
docs.helium CLI wallet elaboration

### ISSUE THREAD

**Issue by Senterium** [helium/docs#690]
The help command returns pretty brief instructions. Would be helpful if it was more elaborative or docs.helium elaborated more extensively on each command, common errors with such commands, ect. docs.helium does pretty well explaining a few commands.

For example I would imagine the "upgrade" command would "Upgrade to the latest basic wallet format" was the function to update the wallet to the newest version. Would like a snippet on each command in docs.helium so I can consume less senior engineer time with github issue submissions.

Discord admins throw shade at queries that seem simple and email support declines to assist. Extensive step-by-step docs, this is the way.

**Comment by samgutentag** [comment]
Closing old issues, See https://docs.helium.com/wallets/cli-wallet for latest CLI Wallet docs.
