### ISSUE TITLE
Add unit of measure for all amounts to the Introduction

### ISSUE THREAD

**Issue by HeliumMonitor** [helium/docs#715]
It is unclear what units the amounts return by endpoints like `GET https://api.helium.io/v1/accounts/:address/stats` are in. Is it in HNT, 1e-8 HNT, 1e-10 HNT, 1e-16 HNT, etc. It would be very helpful if it said what to divide by in the API documents to get amounts in HNT directly. 

It appears that the correct answer is **divide by 100000000 (i.e. 1e8).**

**Comment by PharkMillups** [comment]
Correct. API will return the amount of HNT in bones. There are 100000000 bone per HNT. Can we make this more clear in the docs somehow?

**Comment by HeliumMonitor** [comment]
I think adding this to the Introduction and/or the first endpoint on each page that returns an "amount" field would be extremely helpful. As far as I can tell, the API docs don't mention this at all currently.

**Comment by samgutentag** [comment]
Thank you for calling this out. Information has been added to the documentation and this issue is closed by #911
