### ISSUE TITLE
Mention other mapping systems

### ISSUE THREAD

**Issue by jpmeijers** [helium/docs#718]
We do not want to fragment the mapping effort, but there are other mapping systems out there too. All providing a different view on the same data.

The mapping docs references the official Helium mapper:
docs/use-the-network/coverage-mapping/coverage-mapping.mdx

Is there maybe somewhere a place where we can mention other mapping efforts like [coveragemap.net](coveragemap.net) (TTN Mapper) too?

**Comment by PharkMillups** [comment]
That's a great question. We should likely include them in some capacity. @jthiller What do you think?

**Comment by jthiller** [comment]
Yea, I think that would be a great addition to the mappers doc.
I don't think we call out Cargo as a tool for mapping right now either, so we can probably build out a section that goes into some detail on both.
@jpmeijers up to the PR?
