### ISSUE TITLE
GET 'https://console.helium.com/api/v1/labels fails with Error 500

### ISSUE THREAD

**Issue by FR-ADDIX** [helium/docs#726]
curl --location --request GET 'https://console.helium.com/api/v1/labels' \
--header 'Key: <myconsolenkey>'

The query always ends with an Error 500 in the hosted console.

**Comment by samgutentag** [comment]
are you using the Foundation console? If so there is no API access

https://docs.helium.com/use-the-network/console/hosting-providers/

**Comment by samgutentag** [comment]
Closing: the free to use Foundation Console [does not support the Console API](https://docs.helium.com/api#:~:text=does%20not%20support%20the%20Console%20API)
