### ISSUE TITLE
Issue finding Developer and Browse Devices

### ISSUE THREAD

**Issue by hpssjellis** [helium/docs#740]
I develop devices. The point of the Helium network is to support information flow between ```Devices``` and ```Users``` while incentivizing the need for access points (The Miners). I was very surprised that "Devices" was not a top level Docs topic. When I did find Devices inside the "Use the Network" tab I was more surprised that the 2 options were:

```
Browse Devices
Quickstart Guides

```

Neither of which interest me as a Developer.  Although I would assume the vast majority of Helium users would be interested in the ```Browse Devices``` section.    

 Inside ```Quickstart Guides``` I found the title changed to ``` Development Quickstart``` which then had the expected list of developer boards, which I will try to make a PR for the ```Arduino Portenta with LoRa Vision Shield``` once I have finished developing it.

```
ST B-L072Z-LRWAN1
Sparkfun Pro RF
Adafruit Feather MO
Heltec Cubecell
Heltec WiFi LoRa 32 V2
RAK Wireless WisBlock Starter

```

My issue is: that I kind of know what I am doing and gave up several times while just trying to finding the information that most users would need to begin using the Helium Network! Should the Docs be changed slightly to make ```Devices``` a main heading or should a third level of bullets be added so that it is more obvious that ```Devices``` leads to more information. Sorry I don't have a solution but thought I would bring the issue to Helium's attention. 

@jthiller 
@jdgemm 

The full link to the Developer Devices is here      https://docs.helium.com/use-the-network/devices/development/quickstart-guides/

**Comment by PharkMillups** [comment]
Hi Jeremy. Thanks for the feedback. Super helpful! Also adding @kent-williams to this thread to see if he has thoughts on how to better organize and extend content here. 

Also feel free to join us in the #documentation channel on discord.gg/helium

**Comment by kent-williams** [comment]
Hi Jeremy, thanks for bringing to our attention! As you well know, Helium encompasses a vast amount of components and caters to several different audiences beyond just providing coverage or using coverage. Our hope was to funnel new users of the docs site from general interests down to specific items. This of course removes some popular items, like devices, from being visible at first. I will be revisiting the overall layout of Devices though soon and I will surely take your input into consideration.

Thanks again!

**Comment by samgutentag** [comment]
Good things come to those who wait? PR #1090  is up to move the devices lists to a more prominent position in the sidebar.

**Comment by samgutentag** [comment]
PR complete and changes have been merged. thanks for hanging in there. more to come!
