### ISSUE TITLE
Transferring Validator to Same Validator Host Different Wallet

### ISSUE THREAD

**Issue by Senterium** [helium/docs#771]
My validator host has a single address for their host validator so when I go to transfer validator to a difference wallet, blocks transaction because ["failed_reason":"{invalid,new_validator_already_exists}"] . Why would you block this from occurring just because the validator is identical? 

How else can I transfer to a new wallet address with the same validator?

Already spent 5$ in transaction fees trying to figure this out.

**Comment by dpgarrick** [comment]
If you have access to the validator then you could generate a new swarm_key to get a new validator address to use for the transfer. Same validator host just a "new" validator

**Comment by cokes518** [comment]
this isn't a documentation issue
