### ISSUE TITLE
IotHub Integration Stopped working

### ISSUE THREAD

**Issue by maxnocker** [helium/docs#777]
The IotHub Integration stopped sending data to my IotHub. Has Helium changed something in the integration and is it possible to provide more detailed error messages?

**Comment by ksaye** [comment]
+1, I now see the same issue:

![image](https://user-images.githubusercontent.com/15837044/159525124-a8e79067-8ab1-44e1-81a0-41d6e407844f.png)

**Comment by cokes518** [comment]
hi, this looks like a console issue - please file an issue there. https://github.com/helium/console/issues
