### ISSUE TITLE
Docker to enable I2C issue (command)

### ISSUE THREAD

**Issue by Hccd2022** [helium/docs#799]
I run docker with below command. It says requires at least 1 argument.
Any problem of the command?

sudo docker run --name /dev/i2c-1  --net host  --privileged  -v /var/run/dbus:/var/run/dbus  --mount type=bind,source=/home/pi/miner/config/docker.config,target=/config/sys.config

"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

**Comment by lthiery** [comment]
You are missing the image name at the end of the command, such as "quay.io/team-helium/miner:miner-arm64_2022.03.07.0_GA".

**Comment by Hccd2022** [comment]
Yes. I do think so. But, I try different place. It shows the same error. Can you point out where to place the image name?

**Comment by Hccd2022** [comment]
Thanks master. I think I made it now. But it looks like it will not quit itself

**Comment by lthiery** [comment]
> Thanks master. I think I made it now. But it looks like it will not quit itself

Try the `-d` option. And consider reviewing the docs here: https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/docker-integration/

**Comment by Hccd2022** [comment]
Thanks. Resolved. 

The last question I met during setup as below. Hope you could solve with me. Thanks.

I already install erlang-nox erlang erlang-dev.
==> Errors loading plugin {grpcbox_plugin,
{git,
"https://github.com/andymck/grpcbox_plugin.git",
{branch,"andymck/ts-master"}}}. Run rebar3 with DEBUG=1 set to see errors.
