### ISSUE TITLE
Proposed menu structure for consumer docs

### ISSUE THREAD

**Issue by cokes518** [helium/docs#80]
Goal: bring over intercom articles that covers mobile app usage, network troubleshooting, FAQ, tabs, etc and consolidate in one place.

Proposed new top-level menus:

Hotspot App
* User Guide
  * what is this app
  * what you can do
  * Hotspot Tab
  * Wallet Tab
  * Notification Tab
  * Settings
* Onboarding Account
* Onboarding Hotspot
* Network Troubleshooting
* FAQ
* etc

Wallets
* Hotspot App
* CLI
* Ledger

**Comment by kent-williams** [comment]
@cokes518 Thoughts on this top level nav placement?

![image](https://user-images.githubusercontent.com/479648/103833724-8c770b00-5036-11eb-9d07-0174ab3be095.png)

**Comment by cokes518** [comment]
I don't hate it

**Comment by kent-williams** [comment]
Mark and I thought it was a good place to start, but open to placing wherever you think makes sense!

**Comment by PharkMillups** [comment]
@cokes518 Are we good with what's proposed above?
