### ISSUE TITLE
Arduino: Error downloading http://resource.heltec.cn/download/package_heltec_esp32_index.json

### ISSUE THREAD

**Issue by ksaye** [helium/docs#816]
Using the http://resource.heltec.cn/download/package_heltec_esp32_index.json in the Additional Board Manager gives me the error:

![image](https://user-images.githubusercontent.com/15837044/159514143-2d8df3ca-fb67-4352-8207-f1a4b604f8bd.png)

I am able to use: https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/releases/download/0.0.5/package_heltec_esp32_index.json

Is there an error or mistake I am making?

Trying to follow: https://github.com/helium/docs/blob/master/docs/use-the-network/devices/development/heltec/wifi-lora-32-v2/arduino.mdx

@kent-williams

**Comment by samgutentag** [comment]
Looks like the latest ESP32 package URL has moved to: 

`https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/releases/download/0.0.5/package_heltec_esp32_index.json` 

Sourced from the [Heltec Docs](https://heltec-automation-docs.readthedocs.io/en/latest/esp32%2Barduino/quick_start.html#via-arduino-board-manager)

Will be updated in the Helium Docs with #905
