### ISSUE TITLE
Document Console notifications

### ISSUE THREAD

**Issue by jdgemm** [helium/docs#83]
Internal id: 9401

**Comment by PharkMillups** [comment]
Full list of what needs documenting:

• A device has been deleted.
• An integration with devices is deleted
• An integration with devices is updated
• An integration stops working
• A device connects to an integration for first time
• A downlink is unsuccessful
• A device joins via OTAA for the first time.
• A device stops transmitting for a defined period of time (customize to select minutes or hours)

**Comment by PharkMillups** [comment]
Looks like these finally made it to prod. I'll pick this up.
