### ISSUE TITLE
Erori hilium explorer

### ISSUE THREAD

**Issue by Crisatian** [helium/docs#856]
Hello, I also have a question, why are the hospices that are turned off and no sign of 5 connections removed?
, 10 months what is the meaning of the hexes that, I would like to investigate the situation, I'm sure I'm not the only one, maybe you can help me with this problem, a pleasant day at the mine. , bucresti.

**Comment by PharkMillups** [comment]
Hi there. This is a better question for the #explorer channel on discord. Please follow up there. Thanks.
