### ISSUE TITLE
Deploying Console: outdated docs as source says not to use Auth0

### ISSUE THREAD

**Issue by bsodmike** [helium/docs#880]
Dear all,

Please cast your eyes on this documentation https://github.com/helium/docs/blob/master/docs/use-the-network/run-a-network-server/deploy-console.mdx which talks about using Auth0.

However, the [latest source clearly indicates](https://github.com/helium/console/blob/master/templates/.env#L23) that new deployments should not use Auth0.

It also seems the only need for the nginx proxy in the Docker configurations is to us LetsEncrypt to terminate the Console (public) traffic in TLS for security reasons of course.

However, if one is to use the Magic link, anyone can log in.  This means we should only access Console over a SSH tunnel (as [described in the setup docs](https://deploy-preview-846--helium-docs.netlify.app/use-the-network/run-a-network-server/run-console#run-it)).

**Comment by samgutentag** [comment]
With the migration to the Solana blockchaing and Chirpstack, these docs are undergoing a major overhaul.  Thank you so much for the information, it will be included where relevant in future docs.
