### ISSUE TITLE
Documentation - 'Packet Configurations' needs more info.

### ISSUE THREAD

**Issue by mcdent** [helium/docs#923]
The document at
https://docs.helium.com/use-the-network/console/multi-packets
Which talks about multiple packets or packet configurations, needs more info around the actual purpose of this.
The only explanation of setting multiple packets is:-
_Data Credits are only spent for uplinks including initial join packets. The Multiple Packets feature provides the ability to pay for additional packets for redundancy and location triangulation purposes._

A good explanation of setting it up in the console is given.

**Comment by samgutentag** [comment]
This _is_ the purpose of multi-packets 👍
