### ISSUE TITLE
Troubleshooting Guide: 24 word wallets and Hotspots

### ISSUE THREAD

**Issue by cokes518** [helium/docs#935]
there has been a few users that accidentally transferred their Hotspots from a 12 word wallet to a 24 word wallet.

in this guide, we should outline a few things:

1) if they don't need to assert location or transfer hotspot, leaving it in the 24 word wallet is perfectly safe. just use the maker app to monitor its earnings. HNT will be mined into the 24 word wallet

2) if they need to assert or transfer, it means the owner signature is required. in this case, they should see if their maker app can deeplink into the wallet app. if it can, then use that method to reassert/transfer. As of this writing, only the bobber app supports both blue and black icon apps.

if the maker app cannot deeplink into the wallet app (i.e deeplink only to the blue icon app), then in order to fix this, the user will need to use the CLI, import their 24 words, transfer their hotspots back out to a 12 word wallet (that they control in the blue app) and continue there.

**Comment by waveform06** [comment]
Ive also just put a PR in for the transfer hotspot doc page  and Im mentioning the 24 word issue as well

**Comment by samgutentag** [comment]
closed with #980
