### ISSUE TITLE
Link Preview Images

### ISSUE THREAD

**Issue by kent-williams** [helium/docs#98]
We have the opportunity to add link preview images on an individual doc basis or a global default if nothing is specified in the docs. 

Global Default:
https://v2.docusaurus.io/docs/api/themes/configuration#meta-image

Doc Specific:
`image:`
https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-frontmatter

**Comment by PeterMain** [comment]
@kent-williams is that second link the correct one?

**Comment by kent-williams** [comment]
@PeterMain updated! looks like it got moved to another section.
