### ISSUE TITLE
Create new Device with console API gives 400 Bad Request

### ISSUE THREAD

**Issue by PeterDorsman** [helium/docs#990]
Just tested the possibility to create a new device with the console ap on the eu server (https://console.helium-iot.eu).
A request with just the basic information is giving me a 400 Bad request message. Is the documentation of the Post request Create Device still valid. https://github.com/helium/docs/blob/master/docs/api/console.mdx#create-device
Below here the json I used with SoapUI
```
[{
		"name": "dev01",
		"app_eui": "0AB32232D241ED84",
		"app_key": "00C99767381CBC22A47B3C517A1C9515",
		"dev_eui": "28928821124196EA"
}]
```

**Comment by samgutentag** [comment]
if you are still seeing this issue please post it again in https://github.com/helium/console but also be aware that the existing Helium console will soon be retired in favor of Chirpstack and other LNS systems
